### ISSUE TITLE
Extracting a slice of YML

### ISSUE THREAD

**Issue by juanca** [rubyatscale/code_ownership#107]
I only recently got into using `code_ownership`. My workflow seems to be interested in finding out a particular key-value in the Team YML. 

Would it be a good idea to add a flag to retrieve a bit of YML?

e.g.

```
bin/codeownership for_file --get=some.yml.value some/file/here.js
```

**Comment by ashleywillard** [comment]
Hi @juanca! This isn't an issue that has come up for us. Whenever we've needed specific information about a team, it's been within a ruby script so we'll do something like `CodeOwnership.for_file(file_path).attribute`. We'd be happy to review a PR for this feature if you want to put one up!

**Comment by juanca** [comment]
My teammate provided us with a good bash solution:

```
function who-owns() {
    owner=$(bin/codeownership for_file "$1" | head -1 | cut -c7-)
    config=$(rg -l "$owner" config/teams)
    echo Team: $owner
    yq "$config" | yq '.slack'
}
```
