### ISSUE TITLE
Broken link on blog article

### ISSUE THREAD

**Issue by jimmymeraki** [rubyatscale/code_ownership#14]
Hello! This isn't about the code_ownership gem, but I couldn't find another way to report this. On https://engineering.gusto.com/laying-the-cultural-and-technical-foundation-for-big-rails/ the GitHub links point to the GitHub organization "bigrails" which no longer exists. If you navigate to a specific repository you'll get redirected to the new location under "rubyatscale" but if you follow the link to the org at the bottom of the post you'll get a 404. Also, near the bottom of the article it says "Leave a comment on this blog post" but I'm not seeing any way to leave a comment. There is no contact information for the author of the blog post so I wasn't sure how else to get in touch. Thanks for the article and these gems—they will be useful to my team!

**Comment by AlexEvanczuk** [comment]
@jimmymeraki Thank you for all of the helpful info.
- I've updated the links to point to the `rubyatscale` GitHub org
- We use two blog platforms. Medium, which allows comments (https://medium.com/gusto-engineering/laying-the-cultural-and-technical-foundation-for-big-rails-6b5ab78349ed) and Ghost (https://engineering.gusto.com/laying-the-cultural-and-technical-foundation-for-big-rails/) which doesn't. I didn't realize only one does, so I edited the post on the Ghost article (which I assume is the one you read) to remove the bit about leaving a comment.

Thanks again, and let me know if anything comes up when you start using the gems :)
