### ISSUE TITLE
Missing install documentation for `bin/codeownership`

### ISSUE THREAD

**Issue by sarahsehr** [rubyatscale/code_ownership#70]
Hello!

I am trying to follow the instructions for setting up this gem. After adding the gem to my Gemfile, creating a teams folder, and a `config/code_ownership.yml`, I can run `CodeOwnership.validate!` in the Rails console. However, `bin/codeownership validate` results in `no such file or directory: bin/codeownership`.

I'm wondering if there is a missing step in the instructions or if I have misunderstood the instructions. Thanks!

**Comment by alexevanczuk** [comment]
@sarahsehr I think there may be missing instructions! 

Without additional setup, if a gem has an executable, it can be invoked with `bundle exec name_of_gem`.

To add the `bin/*` command, you need to run `bundle binstubs code_ownership`, [more here](https://bundler.io/v1.13/man/bundle-binstubs.1.html)

**Comment by sarahsehr** [comment]
@alexevanczuk Thanks! I figured it was a binstub command, but was looking in the wrong place.
