### ISSUE TITLE
Define gem ownership

### ISSUE THREAD

**Issue by hmatic** [rubyatscale/code_ownership#95]
Would it be possible to support gem ownership in gemfile?

We have alot of gems in gemfile and I would like each team to handle upgrades and security patches for their own gems.

I don't see a way it would be possible with this gem currently, but maybe I'm missing something.

**Comment by schoblaska** [comment]
Agree, I don't think this is possible currently with `code_ownership`. Is it something you'd be interested in building and submitting a PR for?
